# Course 4: Version Control {-#version-control}

Create an empty repo and name it anything you want.
Go through the repo settings
Delete the repository (warning about what deleting means)
Create a new repo called “my_music_analysis” (make sure you DON’T initiate with readme)
Go to your RStudio.cloud project called my_music_project and push your project to the repository you made above. Follow these instructions https://help.github.com/articles/adding-an-existing-project-to-github-using-the-command-line/
Check your repository on github to see if your project is there.
Make some changes to your repository on github and commit your changes
Go to your project on rstudio.cloud and pull your changes
Go to somebody else’s repository and add an issue there and ask a question about their repo


Look at the website http://jhudatascience.org/chromebookdatascience/
The website is hosted here https://github.com/jhudsl/chromebookdatascience
Fork the repo and then clone it to a new project on rstudio.cloud
Edit the file faq.Rmd. Add just a random line, knit the document and then push it to github.
Go to the repo on jhudsl again and make a pull request.
If you had to summarize what github does in one sentence, how would you describe it?
